CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL DEFAULT '',
    login TEXT NOT NULL DEFAULT '',
    password TEXT NOT NULL DEFAULT '',
    age INTEGER NOT NULL DEFAULT 0,
    review_count INTEGER NOT NULL DEFAULT 0,
    rating INTEGER NOT NULL DEFAULT 0,
    profession TEXT NOT NULL DEFAULT ''
);
-- TODO - Таблица жанров - разделить
CREATE TABLE reviews(
 id SERIAL PRIMARY KEY,
 user_id INTEGER NOT NULL REFERENCES users(id),
 type_id INTEGER NOT NULL REFERENCES types(id),
 genre TEXT NOT NULL DEFAULT '',
 title TEXT NOT NULL DEFAULT '',
 rating INTEGER NOT NULL DEFAULT 0,
 date INTEGER NOT NULL DEFAULT 0,
 review TEXT NOT NULL DEFAULT '',
 likes INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE types(
    id SERIAL PRIMARY KEY,
    type TEXT NOT NULL DEFAULT ''
)